[build]
  base = "."
  publish = "build"
  command = "npm run build"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000
  publish = "build"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/api/*"
  to = "https://jusimples-production.up.railway.app/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/auth/*"
  to = "https://jusimples-production.up.railway.app/auth/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
