[build]
  publish = "frontend/build"
  command = "cd frontend && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy to backend (for development)
# Note: In production, you'll need to deploy backend separately
[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/api/:splat"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https://api.openai.com https://*.openai.com https://*.railway.app https://*.render.com https://*.herokuapp.com; object-src 'none'; base-uri 'self';"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables for frontend build
[context.production.environment]
  REACT_APP_API_URL = "https://jusimples-production.up.railway.app"
  REACT_APP_ENVIRONMENT = "production"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://jusimples-production.up.railway.app"
  REACT_APP_ENVIRONMENT = "preview"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "http://localhost:5000"
  REACT_APP_ENVIRONMENT = "development"
