[variables]
PYTHONPATH = "/app/backend"

[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r backend/requirements.txt"
]

[start]
cmd = "cd /app/backend && . /opt/venv/bin/activate && python app.py"
