[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r backend/requirements.txt"
]

[start]
cmd = "cd backend && python app.py"
