[phases.setup]
nixPkgs = ['python310', 'pip']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'python wsgi.py'

[variables]
PORT = '8080'
FLASK_ENV = 'production'
