[build]
builder = "nixpacks"

[deploy]
startCommand = "python start_backend.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environment]
PYTHONPATH = "/app"
PORT = "8080"
FLASK_ENV = "production"
